---
- :version: = 1.4.0
  :name: highline
- :version: = 2.0.5
  :name: authlogic
- :version: = 1.4.1
  :name: activemerchant
- :version: = 0.0.1
  :name: tlsmail
- :version: = 0.0.6
  :name: active_presenter
- :version: = 0.1.0
  :name: activerecord-tableless
- :version: = 1.15
  :name: calendar_date_select
- :version: = 0.0.2
  :name: schof-searchlogic
- :name: rails
